name: SentinelCheck

on:
  push:
    paths:
      - '*/*/sentinelCheck.yaml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1-59/16 * * * *'

jobs:
  discotest:
    runs-on: ubuntu-18.04
    steps:
      - name: sentinelCheck
        uses: satackey/action-js-inline@v0.0.2
        id: getdata
        with:
          required-packages: axios
          script: |
            const core       = require('@actions/core')
            const axios      = require('axios')
            const response   = await axios('https://api.foojay.io/disco/v1.0/packages/a2a505f4d8956eb730c1ef285b23c269x')
            const json       = response.data
            const available  = (json.hasOwnProperty('id') && json.id === 'a2a505f4d8956eb730c1ef285b23c269')
            const savedState = core.getState("state")
            console.log(`saved state: ${savedState}`)
            console.log(`available: ${available}`)
            core.setOutput('available: ', available)
            if (available) {
              core.saveState("state", 0)
            } else {
              core.saveState("state", 1)
              core.setFailed('Sentinel package not available')
            }