name: SentinelCheck

on:
  push:
    paths:
      - '*/*/sentinelCheck.yaml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */3 * * *'

jobs:
  discotest:
    runs-on: ubuntu-18.04
    steps:
      - name: sentinelCheck
        uses: satackey/action-js-inline@release-master
        id: getdata
        with:
          script: |
            const core    = require('@actions/core')
            const https   = require('https')
            const options = {
              hostname: 'api.foojay.io',
              port: 443,
              path: '/disco/v1.0/packages/a2a505f4d8956eb730c1ef285b23c269',
              method: 'GET'
            }

            const request = https.request(options, response => {
              response.on('data', d => {
                const json      = JSON.parse(d)
                const available = (json.hasOwnProperty('id') && json.id === 'a2a505f4d8956eb730c1ef285b23c269')
                if (available) {
                  core.setOutput('Sentinel package available')
                } else {
                  core.setFailed('Sentinel package not available')
                  core.setOutput('Sentinel package not available')
                }
              })
            })

            request.on('error', error => {
              core.setFailed(error.message)
              core.setOutput(error.message)
            })
      
            request.end()