name: SentinelCheck

on:
  push:
    paths:
      - '*/*/sentinelCheck.yaml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0-59/16 * * * *'

jobs:
  discotest:
    runs-on: ubuntu-18.04
    steps:
      - name: sentinelCheck
        uses: satackey/action-js-inline@v0.0.2
        id: getdata
        with:
          required-packages: axios
          script: |
            const core      = require('@actions/core')
            const axios     = require('axios')
            
            const resp      = await axios('https://api.github.com/repos/foojay2020/discoSentinelCheck/actions/workflows/sentinelCheck.yaml/runs?timestamp=${new Date().getTime()}')
            const respJson  = resp.data
            const lastState = respJson.workflow_runs[0].status
            console.log(`last status: ${lastState}`)
                        
            const response  = await axios('https://api.foojay.io/disco/v1.0/packages/a2a505f4d8956eb730c1ef285b23c269?timestamp=${new Date().getTime()}')
            const json      = response.data
            const available = (json.hasOwnProperty('id') && json.id === 'a2a505f4d8956eb730c1ef285b23c269')
            core.setOutput("available: ", available)
            if (available) {
              console.log(`Sentinel package available`)
            } else {
              var msg = 'Sentinel package not found'
              if (lastState === 'failed') {
                //console.log('Update progress not working!!!')
                msg = 'Sentinel package not found (Update is not working!!!)'
              } else {
                //console.log('Check back in 15 min, failure might be related to automatic remove of sentinel package')
                msg = 'Sentinel package not found (Check back in 15min)'
              }
              //console.log(`Sentinel package not found`)
              core.setFailed(msg)
            }
